version: '3.8'

services:
  web:
    container_name: web_jeromefarin_prod
    build:
      context: ../../
      dockerfile: .docker/prod/Dockerfile
    image: jeromefarin:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jeromefarin.rule=Host(`jeromefarin.fr`)"
      - "traefik.http.routers.jeromefarin.entrypoints=websecure"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
    networks:
      - web

networks:
  web:
    external: true
